### ISSUE TITLE
Issue with keyword arguments

### ISSUE THREAD

**Issue by mhyatt000** [samuela/torch2jax#7]
Hello, thanks for sharing this repo!

I have a problem where keyword arguments are not accepted in the t2j wrapped module:

```
import smplx
mano = smplx.MANOLayer(**cfgs)
mano = t2j(mano)

output = mano(*args, **kwargs)
```

```
File "/home/mhyatt/main.py", line 100, in main
  print(mano(pred['betas'] , pred['hand_pose'], pred['global_orient']))
TypeError: t2j_module.<locals>.f() takes from 1 to 2 positional arguments but 3 were given
```

any thoughts on how I can fix this? Looking forward to your reply

**Comment by mhyatt000** [comment]
added the following support for kwargs:
* did not realize that torch2jax does not support gradient computation, so it no longer fits my use case

```
def t2j_function(f):
    def g(*args, **kwargs):
        return f(*jax.tree_util.tree_map(Torchish, args), **jax.tree_util.tree_map(Torchish, kwargs)).value
    return g


def t2j_module(module):
  def f(*a,  state_dict={}, **k):
    # We want to have a non-mutating API, so we need to copy the module before performing parameter surgery. Note that
    # doing this copy in `t2j_module` and outside of `f` is not sufficient: multiple calls to `f` should not step on
    # each others toes.
    m = copy.deepcopy(module)

    # Can't use torch.func.functional_call due to https://github.com/pytorch/pytorch/issues/110249
    assert state_dict.keys() == dict(m.state_dict()).keys()

    def visit(m, prefix):
      for name, _ in m.named_parameters(recurse=False):
        m._parameters[name] = Torchish(state_dict[".".join(prefix + [name])])

      for name, _ in m.named_buffers(recurse=False):
        m._buffers[name] = Torchish(state_dict[".".join(prefix + [name])])

      # NOTE: named_children() is the non-recursive version of named_modules()
      for name, child in m.named_children():
        visit(child, prefix=prefix + [name])

    # Replace parameters with Torchish objects
    visit(m, prefix=[])

    return t2j_function(m)(*a, **k)

  return f
```

**Comment by samuela** [comment]
> did not realize that torch2jax does not support gradient computation, so it no longer fits my use case

torch2jax supports gradient computation, just not those that include dropout or other stochastic ops (https://github.com/samuela/torch2jax?tab=readme-ov-file#my-pytorch-model-includes-dropout-or-some-other-random-operation-and-does-not-work-in-training-mode-why). this is a known issue, but i have some idea of how to implement it in case folks are interested

> I have a problem where keyword arguments are not accepted in the t2j wrapped module:

do you have a minimal repro of this? the code in the first post requires a 3rd party package and has some undefined variables

**Comment by mhyatt000** [comment]
1. minimal repro is 

```
# t2j(torch.eye(3)) has no problems
t2j(torch.eye(3).unsqueeze(0).unsqueeze(0)) 
```

I think this problem might be more related to `jax from_dlpack`

2. I can open a PR with the amendment for to support kwargs if you would like.

3. would you be able to explain a little more about how the gradient computation is still accurate after converting torch to jax? or point me to a resource where this is discussed?

**Comment by samuela** [comment]
Fixed the unsqueeze issue in https://github.com/samuela/torch2jax/commit/93ed7065c582393384e958ea96f3ad6221b09626
